name: 'Get current package version'
description: 'Get the current version of the setup.py'
branding:
  color: 'gray-dark'
  icon: 'align-center'
inputs:
  path:
    required: false
    default: '.'
    description: 'Path to setup.py file (directories only), e.g. packages/mypackage/'
outputs:
  current-version:
    description: 'Current version defined in the setup.py file'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
