name: Publish

on:
  push:
    tags:
      - 'v*'
env:
  ORG_NAME: aeronext

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.15.3]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm i nexe -g
    - name: create exec file
      run: nexe node_log_exporter.js
    - name: Show files
      run: ls
    - name: Show env
      run: env
    - name: Show env $GITHUB_ACTOR
      run: echo $GITHUB_ACTOR
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: node_log_exporter
        asset_name: node_log_exporter
        tag: ${{ github.ref }}
        overwrite: true
        body: "This is my release text"
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Docker Image
      run: |
          docker build --tag ghcr.io/$ORG_NAME/node_log_exporter:latest \
          --tag ghcr.io/$ORG_NAME/node_log_exporter:$(echo $GITHUB_SHA | head -c7) \
          .
    - name: Push Docker Image
      run: |
          docker push ghcr.io/$ORG_NAME/node_log_exporter:latest
          docker push ghcr.io/$ORG_NAME/node_log_exporter:$(echo $GITHUB_SHA | head -c7)
