name: Create Release

on:
  pull_request:
    types: [closed]
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Docker Image
      env:
        TAG_NAME: ${{ github.event.pull_request.title }}
      run: |
          docker build --tag ghcr.io/$ORG_NAME/node_log_exporter:latest \
          --tag ghcr.io/$ORG_NAME/node_log_exporter:$TAG_NAME \
          .
    - name: Push Docker Image
      env:
        TAG_NAME: ${{ github.event.pull_request.title }}
      run: |
          docker push ghcr.io/$ORG_NAME/node_log_exporter:latest
          docker push ghcr.io/$ORG_NAME/node_log_exporter:$TAG_NAME
